package siliconsloth.miniruler.rules;
dialect  "mvel"

import siliconsloth.miniruler.TitleSelection;
import siliconsloth.miniruler.KeyPress;
import siliconsloth.miniruler.TitleOption;
import siliconsloth.miniruler.Key;

rule "Title Down"
    when
        TitleSelection(option == TitleOption.HOW_TO_PLAY)
        not KeyPress()
    then
        insert(new KeyPress(Key.DOWN))
end

rule "Title Not Down"
    when
        not TitleSelection(option == TitleOption.HOW_TO_PLAY)
        press : KeyPress(key == Key.DOWN)
    then
        delete(press);
end

rule "Title Up"
    when
        TitleSelection(option == TitleOption.ABOUT)
    then
        insert(new KeyPress(Key.UP))
end

rule "Title Not Up"
    when
        not TitleSelection(option == TitleOption.ABOUT)
        press : KeyPress(key == Key.UP)
    then
        delete(press);
end
